// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxyvgljeznsyjxwkelbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4eXZnbGplem5zeWp4d2tlbGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTQ0NDUsImV4cCI6MjA2NTQ3MDQ0NX0.GRB3L-ArMh56wpDO0sK4aaKcvLI3g46HZExiO8yIYPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});